FROM bitnami/mariadb:10.1

# Root mariadb user
ENV MARIADB_ROOT_USER root
ENV MARIADB_ROOT_PASSWORD toor


# User for moodle (match with moodle image)
ENV MARIADB_USER moodle_db_user
ENV MARIADB_PASSWORD moodle_db_password
ENV MARIADB_DATABASE moodle_db
